cd ..\..\
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/aacs.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/abseil.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ace.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ade.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/asiosdk.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ass.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/assimp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/b64.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/bdplus.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/benchmark.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/berkeleydb.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/bluray.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/bookcode.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/boost.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/breakpad.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/brotli.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/bzip2.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/camstudio.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/catch.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/cctz.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/cdio.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/cereal.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ckcore.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ckfilesystem.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ckmmc.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/coin3d.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/cppcoro.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/cpp_demo.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/CrashFix.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/CrashRpt.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/cryptopp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/CSHA1.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/cups.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/curl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/cximage.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dbghelp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dcr.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/Detours.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dirent.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/DirWatcher.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/distorm.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dlib.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dominik-reichl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/double-conversion.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dshow.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/duilib.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dvdcss.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dvdnav.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/dvdread.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/easyexif.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/easySQLite.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/eigen.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/enca.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/event.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/expat.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/fbx.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/fdk-aac.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ffi.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/fftreal.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/flac.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/flite.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/fontconfig.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/freeglut.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/freetype.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/fribidi.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/game-music-emu.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gcrypt.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/getopt.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gif.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/glad.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/glew.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/glfw.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/glib.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/glm.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/glog.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gmock.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gnumake.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gperf.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gpg-error.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gsasl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gsoap.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/gtest.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/hanwenzhi_git.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/hanwenzhi_study.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/hanwenzhi_timeline.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/harfbuzz.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/haru.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/hiberlite.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/hwloc.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/iconv.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/id3.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ilbc.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/intl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ipc.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ittnotify.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/jasper.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/jbig.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/jpeg.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/jpeg-turbo.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/json.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/json-schema-validator.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/jsoncpp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/keepass.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/lame.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/lcms.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/leptonica.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/log4cplus.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/loki.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/lua.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/lzma.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/lzo.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/mcpp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/memcacheclient.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/mfx_dispatch.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/Microsoft_DirectX_SDK_February_2010.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/minilzo.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/miniupnp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/miniz.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/minizip.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/mng.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/mobi.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/modplug.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/nanosvg.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/nasm.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ninja.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ntfstool.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/nvidia_video_sdk_6.0.1.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ogg.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/open3dgc.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/openal.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/opencv.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/openddl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/openddl-parser.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/openexr.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/openjpeg.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/openssl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/opus.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/Pantheios.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/pcre2.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/png.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/poco.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/podofo.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/poly2tri.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/portaudio.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/pq.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/protobuf.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/psd.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/pthread.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/pugixml.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/python.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/qrencode.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/qt.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/qt_linux.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/quirc.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/rapidjson.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/rapidxml.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/re2c.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/resizablelib.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/rtmpdump.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/scintilla.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/sdl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/sigslot.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/Simd.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/sljit.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/slog.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/sndfile.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/soxr.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/spdlog.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/speex.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/spl_sqrt_floor.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/spy.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/sqlite.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/sqlitecpp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ssh.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/StartupManager.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/stb_image.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/stlsoft.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tbb.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tcl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/theora.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tiff.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tightvnc.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tinycthread.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tinygltf.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tinyhttp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tinyxml.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tinyxml2.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/tommath.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/ultravnc.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/unistd.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/UnitTest.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/VC-Logger.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/VirtualMachine.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/vld.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/vorbis.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/webm.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/webp.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/wix.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/wtl.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/wxWidgets.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/xml2.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/xproto.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/yasm.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/yuv.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/zeroc_ice.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/zip.git
git.exe clone --recursive --branch hanwenzhi git@github.com:hwz121212/zlib.git
pause