cd ..\..\
cd aacs & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/aacs.git --allow-unrelated-histories & cd ..
cd abseil & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/abseil.git --allow-unrelated-histories & cd ..
cd ace & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ace.git --allow-unrelated-histories & cd ..
cd ade & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ade.git --allow-unrelated-histories & cd ..
cd asiosdk & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/asiosdk.git --allow-unrelated-histories & cd ..
cd ass & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ass.git --allow-unrelated-histories & cd ..
cd assimp & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/assimp.git --allow-unrelated-histories & cd ..
cd bdplus & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/bdplus.git --allow-unrelated-histories & cd ..
cd benchmark & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/benchmark.git --allow-unrelated-histories & cd ..
cd berkeleydb & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/berkeleydb.git --allow-unrelated-histories & cd ..
cd bluray & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/bluray.git --allow-unrelated-histories & cd ..
cd bookcode & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/bookcode.git --allow-unrelated-histories & cd ..
cd boost & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/boost.git --allow-unrelated-histories & cd ..
cd breakpad & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/breakpad.git --allow-unrelated-histories & cd ..
cd brotli & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/brotli.git --allow-unrelated-histories & cd ..
cd bzip2 & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/bzip2.git --allow-unrelated-histories & cd ..
cd camstudio & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/camstudio.git --allow-unrelated-histories & cd ..
cd catch & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/catch.git --allow-unrelated-histories & cd ..
cd cctz & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/cctz.git --allow-unrelated-histories & cd ..
cd cdio & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/cdio.git --allow-unrelated-histories & cd ..
cd cereal & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/cereal.git --allow-unrelated-histories & cd ..
cd coin3d & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/coin3d.git --allow-unrelated-histories & cd ..
cd cppcoro & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/cppcoro.git --allow-unrelated-histories & cd ..
cd cpp_demo & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/cpp_demo.git --allow-unrelated-histories & cd ..
cd CrashFix & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/CrashFix.git --allow-unrelated-histories & cd ..
cd CrashRpt & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/CrashRpt.git --allow-unrelated-histories & cd ..
cd cups & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/cups.git --allow-unrelated-histories & cd ..
cd curl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/curl.git --allow-unrelated-histories & cd ..
cd cximage & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/cximage.git --allow-unrelated-histories & cd ..
cd dbghelp & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dbghelp.git --allow-unrelated-histories & cd ..
cd dcr & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dcr.git --allow-unrelated-histories & cd ..
cd Detours & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/Detours.git --allow-unrelated-histories & cd ..
cd dirent & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dirent.git --allow-unrelated-histories & cd ..
cd DirWatcher & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/DirWatcher.git --allow-unrelated-histories & cd ..
cd distorm & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/distorm.git --allow-unrelated-histories & cd ..
cd dlib & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dlib.git --allow-unrelated-histories & cd ..
cd dominik-reichl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dominik-reichl.git --allow-unrelated-histories & cd ..
cd double-conversion & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/double-conversion.git --allow-unrelated-histories & cd ..
cd dshow & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dshow.git --allow-unrelated-histories & cd ..
cd duilib & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/duilib.git --allow-unrelated-histories & cd ..
cd dvdcss & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dvdcss.git --allow-unrelated-histories & cd ..
cd dvdnav & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dvdnav.git --allow-unrelated-histories & cd ..
cd dvdread & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/dvdread.git --allow-unrelated-histories & cd ..
cd easyexif & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/easyexif.git --allow-unrelated-histories & cd ..
cd easySQLite & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/easySQLite.git --allow-unrelated-histories & cd ..
cd eigen & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/eigen.git --allow-unrelated-histories & cd ..
cd enca & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/enca.git --allow-unrelated-histories & cd ..
cd event & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/event.git --allow-unrelated-histories & cd ..
cd expat & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/expat.git --allow-unrelated-histories & cd ..
cd fbx & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/fbx.git --allow-unrelated-histories & cd ..
cd fdk-aac & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/fdk-aac.git --allow-unrelated-histories & cd ..
cd ffi & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ffi.git --allow-unrelated-histories & cd ..
cd fftreal & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/fftreal.git --allow-unrelated-histories & cd ..
cd flac & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/flac.git --allow-unrelated-histories & cd ..
cd flite & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/flite.git --allow-unrelated-histories & cd ..
cd fontconfig & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/fontconfig.git --allow-unrelated-histories & cd ..
cd freeglut & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/freeglut.git --allow-unrelated-histories & cd ..
cd freetype & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/freetype.git --allow-unrelated-histories & cd ..
cd fribidi & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/fribidi.git --allow-unrelated-histories & cd ..
cd game-music-emu & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/game-music-emu.git --allow-unrelated-histories & cd ..
cd gcrypt & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/gcrypt.git --allow-unrelated-histories & cd ..
cd getopt & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/getopt.git --allow-unrelated-histories & cd ..
cd gif & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/gif.git --allow-unrelated-histories & cd ..
cd glew & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/glew.git --allow-unrelated-histories & cd ..
cd glfw & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/glfw.git --allow-unrelated-histories & cd ..
cd glib & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/glib.git --allow-unrelated-histories & cd ..
cd glm & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/glm.git --allow-unrelated-histories & cd ..
cd glog & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/glog.git --allow-unrelated-histories & cd ..
cd gmock & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/gmock.git --allow-unrelated-histories & cd ..
cd gperf & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/gperf.git --allow-unrelated-histories & cd ..
cd gpg-error & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/gpg-error.git --allow-unrelated-histories & cd ..
cd gsasl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/gsasl.git --allow-unrelated-histories & cd ..
cd gsoap & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/gsoap.git --allow-unrelated-histories & cd ..
cd gtest & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/gtest.git --allow-unrelated-histories & cd ..
cd hanwenzhi_git & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/hanwenzhi_git.git --allow-unrelated-histories & cd ..
cd hanwenzhi_info & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/hanwenzhi_info.git --allow-unrelated-histories & cd ..
cd hanwenzhi_info_private & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/hanwenzhi_info_private.git --allow-unrelated-histories & cd ..
cd hanwenzhi_timeline & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/hanwenzhi_timeline.git --allow-unrelated-histories & cd ..
cd harfbuzz & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/harfbuzz.git --allow-unrelated-histories & cd ..
cd haru & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/haru.git --allow-unrelated-histories & cd ..
cd hiberlite & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/hiberlite.git --allow-unrelated-histories & cd ..
cd hwloc & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/hwloc.git --allow-unrelated-histories & cd ..
cd iconv & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/iconv.git --allow-unrelated-histories & cd ..
cd id3 & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/id3.git --allow-unrelated-histories & cd ..
cd ilbc & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ilbc.git --allow-unrelated-histories & cd ..
cd intl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/intl.git --allow-unrelated-histories & cd ..
cd ipc & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ipc.git --allow-unrelated-histories & cd ..
cd ittnotify & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ittnotify.git --allow-unrelated-histories & cd ..
cd jasper & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/jasper.git --allow-unrelated-histories & cd ..
cd jbig & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/jbig.git --allow-unrelated-histories & cd ..
cd jpeg & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/jpeg.git --allow-unrelated-histories & cd ..
cd jpeg-turbo & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/jpeg-turbo.git --allow-unrelated-histories & cd ..
cd json & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/json.git --allow-unrelated-histories & cd ..
cd json-schema-validator & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/json-schema-validator.git --allow-unrelated-histories & cd ..
cd jsoncpp & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/jsoncpp.git --allow-unrelated-histories & cd ..
cd lame & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/lame.git --allow-unrelated-histories & cd ..
cd lcms & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/lcms.git --allow-unrelated-histories & cd ..
cd leptonica & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/leptonica.git --allow-unrelated-histories & cd ..
cd loki & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/loki.git --allow-unrelated-histories & cd ..
cd lua & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/lua.git --allow-unrelated-histories & cd ..
cd lzma & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/lzma.git --allow-unrelated-histories & cd ..
cd lzo & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/lzo.git --allow-unrelated-histories & cd ..
cd mcpp & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/mcpp.git --allow-unrelated-histories & cd ..
cd mfx_dispatch & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/mfx_dispatch.git --allow-unrelated-histories & cd ..
cd Microsoft_DirectX_SDK_February_2010 & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/Microsoft_DirectX_SDK_February_2010.git --allow-unrelated-histories & cd ..
cd minilzo & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/minilzo.git --allow-unrelated-histories & cd ..
cd miniupnp & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/miniupnp.git --allow-unrelated-histories & cd ..
cd miniz & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/miniz.git --allow-unrelated-histories & cd ..
cd minizip & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/minizip.git --allow-unrelated-histories & cd ..
cd mng & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/mng.git --allow-unrelated-histories & cd ..
cd mobi & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/mobi.git --allow-unrelated-histories & cd ..
cd modplug & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/modplug.git --allow-unrelated-histories & cd ..
cd nanosvg & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/nanosvg.git --allow-unrelated-histories & cd ..
cd nasm & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/nasm.git --allow-unrelated-histories & cd ..
cd ninja & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ninja.git --allow-unrelated-histories & cd ..
cd ntfstool & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ntfstool.git --allow-unrelated-histories & cd ..
cd nvidia_video_sdk_6.0.1 & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/nvidia_video_sdk_6.0.1.git --allow-unrelated-histories & cd ..
cd ogg & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ogg.git --allow-unrelated-histories & cd ..
cd open3dgc & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/open3dgc.git --allow-unrelated-histories & cd ..
cd openal & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/openal.git --allow-unrelated-histories & cd ..
cd opencv & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/opencv.git --allow-unrelated-histories & cd ..
cd openddl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/openddl.git --allow-unrelated-histories & cd ..
cd openddl-parser & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/openddl-parser.git --allow-unrelated-histories & cd ..
cd openexr & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/openexr.git --allow-unrelated-histories & cd ..
cd openjpeg & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/openjpeg.git --allow-unrelated-histories & cd ..
cd openssl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/openssl.git --allow-unrelated-histories & cd ..
cd opus & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/opus.git --allow-unrelated-histories & cd ..
cd pcre2 & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/pcre2.git --allow-unrelated-histories & cd ..
cd png & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/png.git --allow-unrelated-histories & cd ..
cd poco & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/poco.git --allow-unrelated-histories & cd ..
cd podofo & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/podofo.git --allow-unrelated-histories & cd ..
cd poly2tri & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/poly2tri.git --allow-unrelated-histories & cd ..
cd portaudio & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/portaudio.git --allow-unrelated-histories & cd ..
cd pq & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/pq.git --allow-unrelated-histories & cd ..
cd protobuf & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/protobuf.git --allow-unrelated-histories & cd ..
cd psd & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/psd.git --allow-unrelated-histories & cd ..
cd pthread & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/pthread.git --allow-unrelated-histories & cd ..
cd pugixml & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/pugixml.git --allow-unrelated-histories & cd ..
cd python & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/python.git --allow-unrelated-histories & cd ..
cd qrencode & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/qrencode.git --allow-unrelated-histories & cd ..
cd qt & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/qt.git --allow-unrelated-histories & cd ..
cd quirc & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/quirc.git --allow-unrelated-histories & cd ..
cd rapidjson & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/rapidjson.git --allow-unrelated-histories & cd ..
cd rapidxml & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/rapidxml.git --allow-unrelated-histories & cd ..
cd re2c & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/re2c.git --allow-unrelated-histories & cd ..
cd resizablelib & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/resizablelib.git --allow-unrelated-histories & cd ..
cd rtmpdump & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/rtmpdump.git --allow-unrelated-histories & cd ..
cd scintilla & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/scintilla.git --allow-unrelated-histories & cd ..
cd sdl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/sdl.git --allow-unrelated-histories & cd ..
cd sigslot & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/sigslot.git --allow-unrelated-histories & cd ..
cd Simd & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/Simd.git --allow-unrelated-histories & cd ..
cd sljit & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/sljit.git --allow-unrelated-histories & cd ..
cd soxr & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/soxr.git --allow-unrelated-histories & cd ..
cd spdlog & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/spdlog.git --allow-unrelated-histories & cd ..
cd speex & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/speex.git --allow-unrelated-histories & cd ..
cd spl_sqrt_floor & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/spl_sqrt_floor.git --allow-unrelated-histories & cd ..
cd spy & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/spy.git --allow-unrelated-histories & cd ..
cd sqlite & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/sqlite.git --allow-unrelated-histories & cd ..
cd sqlitecpp & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/sqlitecpp.git --allow-unrelated-histories & cd ..
cd ssh & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ssh.git --allow-unrelated-histories & cd ..
cd StartupManager & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/StartupManager.git --allow-unrelated-histories & cd ..
cd stb_image & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/stb_image.git --allow-unrelated-histories & cd ..
cd stlsoft & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/stlsoft.git --allow-unrelated-histories & cd ..
cd tbb & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tbb.git --allow-unrelated-histories & cd ..
cd tcl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tcl.git --allow-unrelated-histories & cd ..
cd theora & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/theora.git --allow-unrelated-histories & cd ..
cd tiff & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tiff.git --allow-unrelated-histories & cd ..
cd tightvnc & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tightvnc.git --allow-unrelated-histories & cd ..
cd tinycthread & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tinycthread.git --allow-unrelated-histories & cd ..
cd tinygltf & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tinygltf.git --allow-unrelated-histories & cd ..
cd tinyhttp & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tinyhttp.git --allow-unrelated-histories & cd ..
cd tinyxml & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tinyxml.git --allow-unrelated-histories & cd ..
cd tinyxml2 & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tinyxml2.git --allow-unrelated-histories & cd ..
cd tommath & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/tommath.git --allow-unrelated-histories & cd ..
cd ultravnc & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/ultravnc.git --allow-unrelated-histories & cd ..
cd unistd & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/unistd.git --allow-unrelated-histories & cd ..
cd UnitTest & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/UnitTest.git --allow-unrelated-histories & cd ..
cd VC-Logger & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/VC-Logger.git --allow-unrelated-histories & cd ..
cd VirtualMachine & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/VirtualMachine.git --allow-unrelated-histories & cd ..
cd vld & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/vld.git --allow-unrelated-histories & cd ..
cd vorbis & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/vorbis.git --allow-unrelated-histories & cd ..
cd webm & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/webm.git --allow-unrelated-histories & cd ..
cd webp & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/webp.git --allow-unrelated-histories & cd ..
cd wix & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/wix.git --allow-unrelated-histories & cd ..
cd wtl & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/wtl.git --allow-unrelated-histories & cd ..
cd wxWidgets & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/wxWidgets.git --allow-unrelated-histories & cd ..
cd xml2 & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/xml2.git --allow-unrelated-histories & cd ..
cd xproto & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/xproto.git --allow-unrelated-histories & cd ..
cd yasm & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/yasm.git --allow-unrelated-histories & cd ..
cd yuv & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/yuv.git --allow-unrelated-histories & cd ..
cd zeroc_ice & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/zeroc_ice.git --allow-unrelated-histories & cd ..
cd zip & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/zip.git --allow-unrelated-histories & cd ..
cd zlib & git fetch --all & git reset --hard hanwenzhi & git.exe pull git@github.com:hwz121212/zlib.git --allow-unrelated-histories & cd ..
pause