cd ..\..\
cd aacs & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd abseil & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ace & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ade & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd asiosdk & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ass & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd assimp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd b64 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd bdplus & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd benchmark & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd berkeleydb & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd bluray & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd bookcode & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd boost & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd breakpad & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd brotli & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd bzip2 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd camstudio & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd catch & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cctz & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cdio & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cereal & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ckcore & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ckfilesystem & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ckmmc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cmake & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd coin3d & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cppcoro & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cpp_demo & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd CrashFix & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd CrashRpt & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cryptopp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd CSHA1 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cups & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd curl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd cximage & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dbghelp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dcr & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd Detours & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dirent & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd DirWatcher & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd distorm & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dlib & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dominik-reichl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd double-conversion & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dshow & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd duilib & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dvdcss & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dvdnav & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd dvdread & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd easyexif & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd easySQLite & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd eigen & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd enca & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd event & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd expat & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd fbx & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd fdk-aac & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ffi & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd fftreal & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd flac & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd flite & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd fontconfig & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd freeglut & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd freetype & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd fribidi & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd game-music-emu & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gcrypt & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd getopt & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gif & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd glad & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd glew & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd glfw & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd glib & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd glm & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd glog & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gmock & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gnumake & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gperf & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gpg-error & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gsasl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gsoap & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd gtest & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd hanwenzhi_git & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd hanwenzhi_study & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd hanwenzhi_timeline & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd harfbuzz & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd haru & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd hiberlite & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd hiredis & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd hwloc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd iconv & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd id3 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ilbc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd intl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ipc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ittnotify & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd jasper & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd jbig & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd jemalloc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd jpeg & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd jpeg-turbo & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd json & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd json-schema-validator & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd jsoncpp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd keepass & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd lame & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd lcms & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd leptonica & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd linenoise & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd log4cplus & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd loki & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd lua & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd lzma & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd lzo & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd mcpp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd memcacheclient & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd mfx_dispatch & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd Microsoft_DirectX_SDK_February_2010 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd minilzo & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd miniupnp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd miniz & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd minizip & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd mng & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd mobi & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd modplug & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd nanosvg & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd nasm & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ninja & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ntfstool & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd nvidia_video_sdk_6.0.1 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ogg & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd open3dgc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd openal & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd opencv & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd openddl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd openddl-parser & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd openexr & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd openjpeg & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd openssl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd opus & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd Pantheios & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd pcre2 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd png & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd poco & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd podofo & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd poly2tri & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd portaudio & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd pq & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd protobuf & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd psd & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd pthread & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd pugixml & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd python & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd qrencode & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd qt & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd qt_linux & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd quirc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd rapidjson & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd rapidxml & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd re2c & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd redis & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd resizablelib & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd rtmpdump & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd scintilla & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd sdl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd sigslot & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd Simd & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd sljit & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd slog & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd sndfile & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd soxr & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd spdlog & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd speex & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd spl_sqrt_floor & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd spy & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd sqlite & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd sqlitecpp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ssh & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd StartupManager & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd stb_image & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd stlsoft & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tbb & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tcl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd theora & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tiff & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tightvnc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tinycthread & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tinygltf & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tinyhttp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tinyxml & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tinyxml2 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd tommath & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd ultravnc & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd unistd & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd UnitTest & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd VC-Logger & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd VirtualMachine & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd vld & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd vorbis & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd webm & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd webp & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd wix & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd wtl & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd wxWidgets & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd xml2 & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd xproto & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd XtremeToolkitPro & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd yasm & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd yuv & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd zeroc_ice & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd zip & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
cd zlib & git push -v --progress "origin" hanwenzhi:hanwenzhi & cd ..
pause